spring:
  # 项目名称
  application:
    name: mybatis-demo
  datasource:
    # 切换为德鲁伊数据库连接池
    type: com.alibaba.druid.pool.DruidDataSource
    # 配置数据库连接池信息
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/web01
    username: root
    password: 1223

# mybatis 相关配置
mybatis:
  # 指定Mybatis的Mapper文件
  mapper-locations: classpath:mapper/*.xml
  # 指定Mybatis的实体目录
  type-aliases-package: com.tjy.mybatis.pojo
  # 配置Mybatis的日志输出
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl